apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
    </source>
    <match **>
      @type elasticsearch
      host "elasticsearch-data-0.{{ .Release.Namespace }}.svc.cluster.local"
      port 9200
      logstash_format true
      logstash_prefix fluentd
      flush_interval 10s
    </match>