apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    server.host: "0.0.0.0"
    server.name: "kibana-{{ .Release.Namespace }}"
    elasticsearch.hosts: ["http://elasticsearch-{{ .Release.Namespace }}.default.svc.cluster.local:9200"]