apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appAttributes.service.web.name }}
  # labels:
  #   app: {{ .Values.appAttributes.fullName.web }}
spec:
  type: {{ .Values.appAttributes.service.web.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.appAttributes.service.web.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.appAttributes.fullName.web }}
