apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.appAttributes.issuers.production.name }}
spec:
  acme:
    server: {{ .Values.appAttributes.issuers.production.server }}
    email: {{ .Values.appAttributes.issuers.production.email }}
    privateKeySecretRef:
      name: {{ .Values.appAttributes.issuers.production.name }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.appAttributes.issuers.production.ingressClass }}