apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk
spec:
  destination:
    name: ''
    namespace: efk
    server: 'https://kubernetes.default.svc'
  source:
    path: efk
    repoURL: 'http://35.90.72.69/developer/person-deployment.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        maxDuration: 1m0s
        factor: 2
